#pragma once

enum CliViewMode {
    SERVER_VIEW,
    CLI_APP_VIEW
};

enum CliAppScenes {
    WELCOME_SCREEN,
    MAIN_MENU,
    ADD_NEW_PROJECT_SCENE,
    RENDER_PROJECT_SCENE,
    RENDERING_PROGRESS_SCENE,
    EXIT_SCENE 
};